DROP TABLE bs_dept;

CREATE TABLE BS_DEPT
    (
        ID VARCHAR(50) NOT NULL,
        NAME VARCHAR(100) NOT NULL,
        ORGNO VARCHAR(50) NOT NULL,
        FLAG VARCHAR(50),
        STATUS VARCHAR(50),
        ORGNAME VARCHAR(100),
        CONSTRAINT CC1409067969467 PRIMARY KEY (NAME,ORGNO)
    );