DROP TABLE
    BS_BACKUP;
CREATE TABLE
    BS_BACKUP
    (
        ID VARCHAR(50) NOT NULL ,
        FILENAME VARCHAR(100),
        FILEPATH VARCHAR(200),
        CREATEDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UPDATEDATE TIMESTAMP ,
        STATUS VARCHAR(50),
        FLAG VARCHAR(50),
        PRIMARY KEY (id)
    );