CREATE SEQUENCE jg_user_seq;
CREATE SEQUENCE jg_credential_seq;
CREATE SEQUENCE jg_permission_seq;
CREATE SEQUENCE jg_domain_seq;
CREATE SEQUENCE JG_APP_PRINCIPAL_seq;
CREATE SEQUENCE JG_PRINCIPAL_seq;

ALTER SEQUENCE JG_APP_PRINCIPAL_seq RESTART WITH 100;
ALTER SEQUENCE JG_PRINCIPAL_seq RESTART WITH 100;
ALTER SEQUENCE jg_domain_seq RESTART WITH 100;
ALTER SEQUENCE jg_permission_seq RESTART WITH 500;
ALTER SEQUENCE jg_credential_seq RESTART WITH 1000;
ALTER SEQUENCE jg_user_seq RESTART WITH 100;

CREATE SEQUENCE bs_dictionary_seq;
ALTER SEQUENCE bs_dictionary_seq RESTART WITH 1000;