create table src_bankinfo (
   ID              VARCHAR(50)            not null,
   A               VARCHAR(100),
   B               VARCHAR(200),
   C               VARCHAR(100),
   D               VARCHAR(100),
   E               VARCHAR(100),
   F               VARCHAR(100),
   G               VARCHAR(100),
   H               VARCHAR(100),
   I               VARCHAR(200),
   J               VARCHAR(100),
   K               VARCHAR(200),
   L               VARCHAR(100),
   M               VARCHAR(100),
   N               VARCHAR(100),
   O               VARCHAR(100),
   P               VARCHAR(100),
   Q               VARCHAR(100),
   R               VARCHAR(100),
   S               VARCHAR(100),
T               VARCHAR(100),
U               VARCHAR(100),
V               VARCHAR(100),
W               VARCHAR(100),
X               VARCHAR(100),
Y               VARCHAR(100),
Z               VARCHAR(500),
AA               VARCHAR(100),
AB               VARCHAR(100),
AC               VARCHAR(100),
AD               VARCHAR(100),
AE               VARCHAR(100),
AF               VARCHAR(100),
AG               VARCHAR(100),

   constraint P_Key_1 primary key (ID)
);