delete from BS_ADMENFORCE;
delete from BS_ADMPUNISH;
delete from BS_ADMPUNISHCONS;
delete from BS_AECONCLUSION;
delete from BS_AEINSPECTION;
delete from BS_AEINSPECTION_ANL;
delete from BS_AERECTIFICATION;
delete from BS_FACTBOOK;
delete from BS_WORKBASIS;
delete from BS_WORKCOMING;
delete from BS_WORKGOAWAY;
delete from BS_WORKTALKSUMMARY;
delete from BS_ATTCACHMENTS;

update BS_NOGENERATE set AENOINDEX =1,EVDCNOINDEX =1 ,FACTNOINDEX=1,AWAYNOINDEX=1,PBNSHNOINDEX=1,COMEININDEX=1;