DROP TABLE BS_AEFeedback;
CREATE TABLE BS_AEFeedback
    (
        ID VARCHAR(50) NOT NULL,
        AENO VARCHAR(50) NOT NULL,
        AEORGNM VARCHAR(100) NOT NULL,
        AEORGNO VARCHAR(50) NOT NULL,
        AEEDORGNM VARCHAR(100) NOT NULL,
        AEEDORGNO VARCHAR(50) NOT NULL,
        
        TopLevelBankNm VARCHAR(100),
        TopLevelBankNo VARCHAR(50),
        DirectParentlBankNm VARCHAR(100),
        DirectParentlBankNo VARCHAR(50),
        FeedbackOpnion CLOB,
        FeedbackDate TIMESTAMP,
        
        CREATOR VARCHAR(50),
        CREATORORG VARCHAR(100),
        CREATORORGNO VARCHAR(50),
        CRTDATE TIMESTAMP,
        STAT VARCHAR(50),
        FLAG VARCHAR(50),
        CREATEDATE TIMESTAMP,
        UPDATEATE TIMESTAMP,
        CRTLOGIN VARCHAR(100),
        AEEDORGZZNO VARCHAR(50),
        AEEDORGXZHNO VARCHAR(50),
        AEEDORGZZNM VARCHAR(100),
        AEEDORGXZHNM VARCHAR(100),
        ISFINISHED INTEGER,
        ISFINISH CHARACTER(1),
        CANBEUPDATE CHARACTER(1),
        AEEDORGBANKTYPE VARCHAR(50),
        CONSTRAINT P_KEY_1 PRIMARY KEY (ID)
    );
    
    
DROP TABLE BS_AEPubnishFeedback;
CREATE TABLE BS_AEPubnishFeedback
    (
        ID VARCHAR(50) NOT NULL,
        AENO VARCHAR(50) NOT NULL,
        AEORGNM VARCHAR(100) NOT NULL,
        AEORGNO VARCHAR(50) NOT NULL,
        AEEDORGNM VARCHAR(100) NOT NULL,
        AEEDORGNO VARCHAR(50) NOT NULL,
        
        TopLevelBankNm VARCHAR(100),
        TopLevelBankNo VARCHAR(50),
        DirectParentlBankNm VARCHAR(100),
        DirectParentlBankNo VARCHAR(50),
        FeedbackOpnion CLOB,
        FeedbackDate TIMESTAMP,
        
        CREATOR VARCHAR(50),
        CREATORORG VARCHAR(100),
        CREATORORGNO VARCHAR(50),
        CRTDATE TIMESTAMP,
        STAT VARCHAR(50),
        FLAG VARCHAR(50),
        CREATEDATE TIMESTAMP,
        UPDATEATE TIMESTAMP,
        CRTLOGIN VARCHAR(100),
        AEEDORGZZNO VARCHAR(50),
        AEEDORGXZHNO VARCHAR(50),
        AEEDORGZZNM VARCHAR(100),
        AEEDORGXZHNM VARCHAR(100),
        ISFINISHED INTEGER,
        ISFINISH CHARACTER(1),
        CANBEUPDATE CHARACTER(1),
        AEEDORGBANKTYPE VARCHAR(50),
        CONSTRAINT P_KEY_1 PRIMARY KEY (ID)
    );
