ALTER TABLE BS_ORG ADD COLUMN ISLEAF VARCHAR (10) ;
UPDATE BS_ORG SET ISLEAF='0' ;
UPDATE BS_ORG SET ISLEAF='1' WHERE NO NOT IN (SELECT PARENTNO FROM BS_ORG);

ALTER TABLE BS_SURVEYOBJECT ADD COLUMN PROVINCE VARCHAR (10) ;
ALTER TABLE BS_SURVEYOBJECT ADD COLUMN CITY VARCHAR (10) ;
ALTER TABLE BS_SURVEYOBJECT ADD COLUMN COUNTRY VARCHAR (10) ;
UPDATE BS_AREA SET ISLEAF='0' ;
UPDATE BS_AREA SET ISLEAF='1' WHERE ID NOT IN (SELECT PARENT FROM BS_AREA);