ALTER TABLE
    BS_WORKBASIS ALTER FILED1 SET data type VARCHAR(458);
ALTER TABLE
    BS_WORKBASIS ALTER FILED2 SET data type VARCHAR(458);
ALTER TABLE
    BS_WORKBASIS ALTER FILED3 SET data type VARCHAR(458);
ALTER TABLE
    BS_WORKBASIS ALTER FILED4 SET data type VARCHAR(458);
ALTER TABLE
    BS_WORKBASIS ALTER FILED7 SET data type VARCHAR(458);
ALTER TABLE
    BS_WORKBASIS ALTER FILED8 SET data type VARCHAR(458);
ALTER TABLE
    BS_WORKBASIS ALTER FILED10 SET data type VARCHAR(458);



ALTER TABLE
    BS_WORKCOMING ALTER FILED3 SET data type VARCHAR(458);
ALTER TABLE
    BS_WORKCOMING ALTER FILED6 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKCOMING ALTER FILED7 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKCOMING ALTER FILED8 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKCOMING ALTER FILED11 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKCOMING ALTER FILED12 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKCOMING ALTER FILED13 SET data type VARCHAR(255);

ALTER TABLE
    BS_WORKGOAWAY ALTER FILED4 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKGOAWAY ALTER FILED5 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKGOAWAY ALTER FILED6 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKGOAWAY ALTER FILED10 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKGOAWAY ALTER FILED12 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKGOAWAY ALTER FILED14 SET data type VARCHAR(255);
ALTER TABLE
    BS_WORKGOAWAY ALTER FILED15 SET data type VARCHAR(255);

ALTER TABLE
    BS_WORKTALKSUMMARY ALTER FILED3 SET data type VARCHAR(150);
ALTER TABLE
    BS_WORKTALKSUMMARY ALTER FILED4 SET data type VARCHAR(150);
ALTER TABLE
    BS_WORKTALKSUMMARY ALTER FILED9 SET data type VARCHAR(200);
ALTER TABLE
    BS_WORKTALKSUMMARY ALTER FILED13 SET data type VARCHAR(150);
ALTER TABLE
    BS_WORKTALKSUMMARY ALTER FILED14 SET data type VARCHAR(300);
ALTER TABLE
    BS_WORKTALKSUMMARY ALTER FILED15 SET data type VARCHAR(150);







 



ALTER TABLE
    BS_WORKCOMING ALTER FILED9 SET data type VARCHAR(100);
ALTER TABLE
    BS_WORKTALKSUMMARY ALTER FILED11 SET data type VARCHAR(120);
ALTER TABLE
    BS_WORKTALKSUMMARY ALTER FILED14 SET data type VARCHAR(200);
ALTER TABLE
    BS_WORKBASIS ALTER FILED10 SET data type VARCHAR(380);
ALTER TABLE
    BS_WORKBASIS ALTER FILED9 SET data type VARCHAR(100);
ALTER TABLE
    BS_AEINSPECTION_ANL ALTER REPORTER SET data type VARCHAR(100);
ALTER TABLE
    BS_AEINSPECTION ALTER CREATOR SET data type VARCHAR(100); 
        