INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('PCB', '中国人民银行', '0', null, null, null, null, null, null, 'PCB', '中国人民银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('GYSYYH', '国有商业银行', '0', null, null, null, null, null, null, 'GYSYYH', '国有商业银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('OTHER', '其他', '0', null, null, null, null, null, null, 'OTHER', '其他', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('QGXGFZSYYH', '股份制商业银行', '0', null, null, null, null, null, null, 'QGXGFZSYYH', '股份制商业银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('XFJRGS', '消费金融公司', '0', null, null, null, null, null, null, 'XFJRGS', '消费金融公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('ZCXYH', '政策性银行', '0', null, null, null, null, null, null, 'ZCXYH', '政策性银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('SWCSSYYH', '省外城市商业银行', '0', null, null, null, null, null, null, 'SWCSSYYH', '省外城市商业银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('CSSYYH', '省内城市商业银行', '0', null, null, null, null, null, null, 'CSSYYH', '省内城市商业银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('NCSYYH', '农村商业银行', '0', null, null, null, null, null, null, 'NCSYYH', '农村商业银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('NCXYHZS', '四川省农村信用联社', '0', null, null, null, null, null, null, 'NCXYHZS', '农信社', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('GJJGLZX', '公积金管理中心', '0', null, null, null, null, null, null, 'GJJGLZX', '公积金管理中心', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('CZYH', '村镇银行', '0', null, null, null, null, null, null, 'CZYH', '村镇银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('ZCGLGS', '资产管理公司', '0', null, null, null, null, null, null, 'ZCGLGS', '资产管理公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('BXGS', '保险公司', '0', null, null, null, null, null, null, 'BXGS', '保险公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('XEDKGS', '小额贷款公司', '0', null, null, null, null, null, null, 'XEDKGS', '小额贷款公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('ZQGS', '证券公司', '0', null, null, null, null, null, null, 'ZQGS', '证券公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('RJXDBGS', '融资性担保公司', '0', null, null, null, null, null, null, 'RJXDBGS', '融资性担保公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('WZSYYH', '外资银行', '0', null, null, null, null, null, null, 'WZSYYH', '外资银行', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('ZXJG', '征信机构', '0', null, null, null, null, null, null, 'ZXJG', '征信机构', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('DKGS', '贷款公司', '0', null, null, null, null, null, null, 'DKGS', '贷款公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('CWGS', '财务公司', '0', null, null, null, null, null, null, 'CWGS', '财务公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);
INSERT INTO BS_ORG (NO, NAME, PARENTNO, PARENTNAME, ISPCB, ORGCODEOFZZ, ORGCODEOFXY, PCBNO, PCBNAME, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, ORGSTATUS, AH) VALUES ('XTGS', '信托投资公司', '0', null, null, null, null, null, null, 'XTGS', '信托投资公司', null, null, null, null, null, null, null, '0', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '启用', null);


update bs_org set ispcb = 'YES' where d = 'A';